FROM arm32v7/golang:alpine

RUN apk add --no-cache \
		ca-certificates

RUN apk -v --update add \
	  bash \
	  git \
    curl \
    make \
    gcc \
    musl-dev \
    openssl \
    go \
    python \
    py-pip \
    feh \
    rm -f /var/cache/apk/*


RUN cd /go && \
    go get -u github.com/FiloSottile/mkcert && \
    cd src/github.com/FiloSottile/mkcert && \
    go build -o /bin/mkcert

WORKDIR /root/.local/share/mkcert

CMD mkcert -install && for i in $(echo $domain | sed "s/,/ /g"); do mkcert $i; done && tail -f -n0 /etc/hosts
